### PR TITLE
Add support for .leet.toml

### PR DESCRIPTION
**Pull request by Antosser**
This PR adds support for the `.leet.toml` thing.

This is how it works right now:  
`cargo leet active` prints the currently active problem.  
`cargo leet active [slug]` sets the currently active problem, checking that it exists and that it isn't `lib`.  
`cargo leet test` prepends `//` to every `(pub) mod [slug];` and runs `cargo test` before reverting `lib.rs`

I'd also add the copying subcommand, but now that I switched to KDE on Wayland on Arch, btw, at least for now, I can't get it working

### CODE REVIEW

**Comment by c-git** [comment]
Thanks, I'll check it out.

**Comment by c-git** [comment]
Really good PR. Thank you very much. I think it is mostly fine, there are a few minor nits that I would want but I wouldn't hold it up for those. The only thing I'd want to do before merging is move the copy code into a separate branch until we can get it working instead of merging in code that doesn't work yet if that's ok with you.

Also do you want me to add you to the organization so you can just create branches directly on the repo?

**Comment by Antosser** [comment]
> Really good PR

Thx ^^

> there are a few minor nits that I would want but I wouldn't hold it up for those

I'd happily fix them

> move the copy code into a separate branch

To be clear, I only tried it out in this branch. The copy code isn't actually included in this PR

> Also do you want me to add you to the organization so you can just create branches directly on the repo?

That would be great, thanks

**Comment by c-git** [comment]
> I'd happily fix them

Sure it's just two actually now that I look at the list. It's to move ".leet.tom" into a constant so that if we ever need to change it we minimize the number of places that needs to happen and to update the readme but that one can wait as I kinda want to restructure it to be more maintainable.

> To be clear, I only tried it out in this branch. The copy code isn't actually included in this PR

That explains why I didn't notice it

**Review by c-git — APPROVED** [review]

**Pull request merged**
